### ISSUE TITLE
MinimalLayerSeeder - zle vkladá strom vrstiev

### ISSUE THREAD

**Issue by mspiderv** [next-dimension-team/3duml#51]
Ak seednem dva krát tento seeder, tak mi priradí všetky 4 layery do prvého diagramu. Malo by priradiť 2 layery do prvého diagramu a zvyšné 2 do druhého diagramu.

**Comment by Ruby184** [comment]
Problém je na riadku https://github.com/next-dimension-team/3duml/blob/master/database/seeds/MinimalLayerSeeder.php#L29
`save()` vracia `true`, čo sa pretypuje na 1 a tak je ` $rootInteractionFragment` stále 1

**Comment by Ruby184** [comment]
Fixed by #57
