### ISSUE TITLE
Pri operacii "rename" je to policko povinne

### ISSUE THREAD

**Issue by mspiderv** [next-dimension-team/3duml#91]
Ak nezadam ziadny text nefunguje to dobre. V konzole vidim XHR s HTTP statusom 422 lebo vacinou je ten nazov povinny. Prosim opravit to tak ze ked nezadam ziadny nazov aby sa nevykonala ziadna akcia.

**Comment by peterzajac39** [comment]
https://scotch.io/tutorials/angularjs-form-validation

**Comment by mspiderv** [comment]
@peterzajac39 to je pre angular 1 :(

**Comment by peterzajac39** [comment]
ok dik ja som si to len tak znacil zatial

**Comment by peterzajac39** [comment]
opravene v develoopmente
